IN THIS LECTURE WE GOT BRIEF INTRODUCTION OF POINTERS.
POINTERS : THEY ARE VARIABLES THAT STORES MEMORY ADDRESS OF ANOTHER VARIABLES.
DIFFERENCE BETWEEN VARIABLE AND POINTERS: VARIABLES ARE USED TO STORE VALUE WHILE POINTERS ARE USED TO STORE ADDRESS.
TYPES OF POINTERS: POINTER POINTING TO AN ELEMENT.

int* = THIS IS POINTER WHICH STORE ADDRESS OF INT VARIABLE.
float* = THIS IS POINTER WHICH CAN STORE ADDRESS OF FLOAT VARIABLE.

USAGE: REDUCES THE LENGTH AND COMPLEXITY OF THE CODE.
       ENABLE TO ACCESS VARIABLE OUTSIDE THE PROGRAM.


int a=3;
address = abcd

whenever we initialize a variable and assign a value to it a space is allocated to it in memory whiich is stored at address "abcd".
POINTER STORING THE ADDRESS OF a:- 
int *p.
p = &a;
  


#include<iostream>
using


  
