IN THIS LECTURE I HAVE LEARNT ABOUT FEW IMPORTANT TERMS LIKE:
SYNTAX - IT REFERS TO SET OF RULES AND PRINCIPLES THAT GOVERN THE STRUCTURE AND COMPOSITION OF STATEMENTS IN PROGRAMMING LANGUAGE.
PROGRAMMING LANGUAGE  IS REQUIRED TO COMMUNICATE WITH THE COMPUTER.
MOREVER I HAVE LEARNT TO WRITE MY FIRST C++ CODE(HELLO WORLD):

#include <iostream>
using namespace std;
int main(){
  cout<<"Hello World";
  return 0;
}

ALSO I HAVE LEARNT ABOUT DIFFERENCE BETWEEN DISPLAYING AND OUTPUT.
 DISPLAYING MEANS PRINTING OR WHAT YOU DISPLAY ON THE SCREEN, JUST LIKE WHAT WE DID IN THE ABOVE CODE.
 OUTPUT MEANS WHAT COMPUTER PROCESSES AND GIVES OUT FOR THAT PARTICULAR FUNCTION. 

