SELECTION SORT:- IT A SORTING ALGORITHM THAT REPEATEDLY FINDS THE SMALLEST/LARGEST ELEMENT FROM UNSORTED PART OF THE LIST AND SWAP IT WITH FIRST UNSORTED ELEMENT.
TIME COMPLEXITY OF SELECTION SORT:- O(n^2)
SPACE COMPLEXITY OF SELECTION SORT:- O(1)  
SORTING:- ARRANGING THE ELEMENTS IN A SPECIFIC ORDER.(DEPENDING ON AESCENDING OR DESCENDING).

EXAMPLE:- 3 5 2 1 4
          1 5 2 3 4
          1 2 5 3 4
          1 2 3 5 4
          1 2 3 4 5  // SORTED....
  
