FROM THIS LECTURE THE CONCEPT OF ALGORITHMS STARTS.
ALGORITHMS:- PROCEDURE WE SHOULD FOLLOW FOR A PARTICULAR PROBLEM SO THAT WE CAN ARRIVE AT A SOLUTION.
OR IN SHORT WE CAN SAY IT IS SOLUTION FOR A PARTICULAR PROBLEM IN EFFICIENT WAY.

DIFFERENT KINDS OF ALGORITHMS:- 
 1.SORTING
 2.SEARCHING
 3.RECURSION
 4.GREEDY
 5. DYNAMIC PROGRAMMING
 6.GRAPH ALGORITHMS
 7. BACK-TRACKING ALGORITHMS
  
