THIS LECTURE IS ABOUT MODES OF INHERITANCE.
BASE CLASS: DERIEVED CLASS
PUBLIC MODE: IF WE DERIEVE A SUBCLASS FROM PUBLIC BASE CLASS.
PROTECTED MODE: IF WE DERIEVE A SUBCLASS FROM PROTECTED BASE CLASS.

1. POLYMORPHISM:- ABLITY OF AN OBJECT TO TAKE MANY FORMS.
  TYPES: COMPILE TIME POLYMORPHISM - IT IS ACHIEVED BY FUNCTION OVERLOADING AND OPERATOR OVERLOADING.
         RUNTIME POLYMORPHISM - IT IS ACHIVEVED BY FUNCTION OVERRIDING AND VIRTUAL FUCTION.

Q) WHAT IS FUNCTION OVERLOADING?
 ANS: IT IS A FEATURE THAT ALLOWS MULTIPLE FUNCTIONS TO HAVE SAME NAME AND PERFORM RELATED TASKS BUT WITH DIFFERENT PARAMETERS.

Q) WHAT IS OPERATOR OVERLOADING ?
ANS: OPERATOR OVERLOADING ALLOWS OPERATOR TO BE REDEFINED IN DIFFERENT WAYS DEPENDING ON OPERANDS.
