THIS IS INTRODUCTORY VIDEO ON ANALYSIS OF ALGORITHM.
TO ANALYSE DATA WE SHOULD BE ABLE TO SORT IT.
IF THE SIZE OF DATA INCREASES, THEN AUTOMATICALLY THE AMOUNT OF TIME TO ANALYSE THE DATA ALSO INCREASES.
WE NEED EFFICIENT ALGORITHM TO ANALYSE THE DATA.
ALGORITHM IS ANALYSED BASES ON NUMBER OF LINES OF CODE.  
