IN THIS LECTURE I HAVE LEARNT ABOUT BRIEF SUMMARY OF FUNCTION.
FUNCTIONS:- IT IS SOMETHING THAT CARRIES OUT SPECIFIC OR WELL-DEFINED TASKS.

WHY FUNCTIONS ARE IMPORTANT:-
1) DIVIDE AND CONQUEROR
2) REUSE - WRITE ONCE AND USE ANYWHERE IN THE PROGRAM.
3)ABSTRACTION - HIDE INTERNAL DETAILS
4)IMPROVES READABLITY OF THE CODE.

FUNCTIONS ARE BASICALLY OF TWO TYPES:-
1) HEADER
2)BODY

int compare(int a, int b)  ----> HEADER FUNCTION,

 HERE "int" IS THE RETURN TYPE OF THE FUNCTION 
EVERY FUNCTION WILL HAVE A RETURN VALUE and RETURN VALUE WILL HAVE A RETURN TYPE.  
