THIS LECTURE IS ALL ABOUT ADDRESS OF ELEMENTS.
THE POSITION OF DATATTYPE IN MEMORY.
ADDRESS OF ELEMENT REFERS TO MEMORY LOCATION WHERE THAT ELEMENT IS STORED.
EVERY VARIABLE OR OBJECT IN C++ IS ASSIGNED A UNIQUE MEMORY ADDRESS.
DONE WITH THE HELP OF "&" - OPERATOR.

#include<iostream>
using namespace std;
int main(){
  int a;
  long long int b;
  cout<<&a<<&b;
  return 0;
}

SO HEXADECIMAL - 0 TO 9 AND THEN A TO F.
  HEXADECIMAL CONVERSIONS:
  DECIMAL TO HEXADECIMAL- 1234/16 = 77 REM=2
                          77/16 = 4    REM=13
                          4/16 = 0     REM=4
  ANS = 4D2
ADDRESS OF ELEMENT IS REPRESENTED IN HEXADECIMAL.
