IN THIS LECTURE, I LEARNED ABOUT INTRODUCTION TO C++.
C++ IS MORE EFFICIENT,STRONG ABSTRACTION CAPABLITIES AND STANDARD TEMPLATE LIBRARY(STL) AND IT'S COMPILE TIME CHECKS.
THAT'S ALL ABOUT LECTURE 1.
