IN THIS LECTURE I HAVE LEARNT ABOUT LOOPS.
LOOP IS SOMETHING WHICH REPEATS ITSELF.
SIMILAR ACTION IS REPEATED.
FOR IMPLEMENTING LOOP:- 
ACTION IN LOOP SHOULD BE DECIDED BY US AND CAN BE CHANGED IN EVERY LOOP.
HOW MANY TIMES A LOOP IS GOING TO RUN.

FOR LOOP SYNTAX: 
for(intialization;condition;update){
    //code
}
WHAT ACTION IS HAPPENING MOSTLY DEPENDS UPON WHICH ITERATION IT IS ON.


                      
