IN THIS LECTURE I HAVE LEARNT ABOUT VARIABLES AND CONSTANTS.
  VARIABLES- IT VARIES AND IT'S VALUE CHANGES.
  CONSTANTS- REMAINS SAME IRRESPECTIVE OF WHO IS USING IT.
  DATATYPE- IT DEFINES THE TYPE OF VARIABLE WHICH IS BEING DECLARED.

 RULES FOR VARIABLE INITILISATION:-
 1.MUST BEGIN WITH ALPHABET(A-Z OR a-z) or underscore(_).
 2.IN THE SECOND PLACE THERE CAN BE ALPHABET(A-Z or a-z),DIGITS(0-9) OR UNDERSCORE.
 3. IT IS CASE-SENSITIVE.

 ALSO I HAVE LEARNT THERE ARE DIFFERENT KINDS OF DATATYPES LIKE INT, FLOAT,DOUBLE,CHAR ETC.
 USER-DEFINED DATATYPES LIKE STRUCT,CLASS ENUM ETC. 
  
  
